# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64, null=True)),
                ('telephone', models.CharField(max_length=16, null=True)),
                ('open', models.DateTimeField(null=True)),
                ('close', models.DateTimeField(null=True)),
                ('busy', models.DateTimeField(null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('type', models.CharField(choices=[('1', 'RUN'), ('2', 'BADMINTON'), ('3', 'FUTSAL'), ('4', 'SWIM'), ('5', 'GYMNASTIC'), ('6', 'PINGPONG')], max_length=2)),
            ],
        ),
    ]
